version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec danger --verbose
      - run: bundle exec awesome_bot --allow-redirect --allow-dupe -w awesome_bot --allow-redirect --allow-dupe -w regexr,127.0.0.1 `find . -name "*.md"`
