version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec danger --verbose
      - run: bundle exec awesome_bot --allow-redirect --allow-dupe -w awesome_bot --allow-redirect --allow-dupe -w https://github.com/Shift3/ifg/compare/v0.4.0...v0.5.0,https://github.com/Shift3/sinclair-scanner-application,https://github.com/Shift3/sinclair-scanner-application/pull/137,https://github.com/Shift3/FUSDMonitoringAppXamarin,https://github.com/Shift3/rn-by-example,https://github.com/Shift3/fusd-front-desk-kiosk,regexr,https://github.com/Shift3/bw-project-status,https://github.com/Shift3/Aerostar,https://github.com/Shift3/qa-team/projects,https://github.com/Shift3/sundial-mobile-app,https://github.com/Shift3/boilerplate-client-angular#docker,https://github.com/Shift3/boilerplate-server-node/blob/develop/docker-compose.yml,127.0.0.1 `find . -name "*.md"`
